export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-dark-body">
        <div className="flex items-center justify-center min-h-screen">
          {children}
        </div>
      </body>
    </html>
  )
}
