import type { Metadata } from "next";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import GlobalReplyListener from "@/components/comment/global-reply-listener";


export const metadata: Metadata = {
  title: "DNPC",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <GlobalReplyListener />
      <div className="bg-dark-body dark">
        <div className="flex flex-col min-h-screen relative">
          <div className="flex-grow">
            <Header />
            <div className="container mx-auto">
              {children}
            </div>
            <Footer />
          </div>
        </div>
      </div>
    </>

  );
}
