import type { Metadata } from "next";
import { BannerHome } from "@/components/banner/banner-home";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";


export const metadata: Metadata = {
  title: "DNPC",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-dark-body dark">
      <div className="flex flex-col min-h-screen relative">
        <div className="flex-grow">
          <Header />
          {/* <BannerHome /> */}
          <div className="container mx-auto">
            {children}
          </div>
          <Footer />
        </div>
      </div>
    </div>

  );
}
