import type { Metadata } from "next";
import { Potta_One, Zen_Maru_Gothic } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/header";
import { BannerHome } from "@/components/banner/banner-home";



const geistZenMaruGothic = Zen_Maru_Gothic({
  weight: ['500'],
  subsets: ['latin'],
  variable: '--font-zen-maru-gothic'
})
const geistPottaOne = Potta_One({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-potta-one'
})

export const metadata: Metadata = {
  title: "DNPC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistZenMaruGothic.className} ${geistPottaOne.variable} antialiased bg-dark-body`}
      >
        <Header />
        <BannerHome />
        <div className="container mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
