import { Potta_One, Zen_Maru_Gothic, Roboto, Noto_Color_Emoji } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";


const geistZenMaruGothic = Zen_Maru_Gothic({
  weight: ['500', "700", '900'],
  subsets: ['latin'],
  variable: '--font-zen-maru-gothic'
})
const geistPottaOne = Potta_One({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-potta-one'
})
const geistRoboto = Roboto({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-roboto'
})
const geistNotoColorEmoji = Noto_Color_Emoji({
  weight: ['400'],
  subsets: ['emoji'],
  variable: '--font-noto-color-emoji'
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistZenMaruGothic.className} ${geistPottaOne.variable} ${geistRoboto.variable} ${geistNotoColorEmoji.variable} antialiased `}>
        <ThemeProvider attribute={'class'} defaultTheme="dark" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
