import { Potta_One, Zen_Maru_Gothic } from "next/font/google";
import "./globals.css";


const geistZenMaruGothic = Zen_Maru_Gothic({
  weight: ['500'],
  subsets: ['latin'],
  variable: '--font-zen-maru-gothic'
})
const geistPottaOne = Potta_One({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-potta-one'
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${geistZenMaruGothic.className} ${geistPottaOne.variable} antialiased bg-dark-body dark`}>{children}</body>
    </html>
  )
}
